Repository Kernel360/F2-omocha-BE, pull requests merged in 2024-11, with the labels that each got.

#158 [REFACTOR] 채팅 리펙토링
  build.gradle
  omocha-api/build.gradle
  omocha-api/src/main/java/org/omocha/api/application/ChatFacade.java
  omocha-api/src/main/java/org/omocha/api/common/config/SwaggerConfig.java
  omocha-api/src/main/java/org/omocha/api/common/handler/GlobalExceptionHandler.java
  omocha-api/src/main/java/org/omocha/api/common/response/SliceResponseDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuctionApi.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuctionController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/ChatController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/ChatRoomApi.java
  omocha-api/src/main/java/org/omocha/api/interfaces/ChatRoomController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/AuctionDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/ChatDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/ChatDtoMapper.java
  omocha-domain/build.gradle
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/BidServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/Chat.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatInfoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatRoom.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatStore.java
  omocha-domain/src/main/java/org/omocha/domain/common/config/WebSocketConfig.java
  omocha-domain/src/main/java/org/omocha/domain/exception/AuctionImageNotFoundException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/ChatException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/ChatRoomAccessException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/ChatRoomAlreadyExistException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/ChatRoomNotFoundException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ChatCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ImageCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/SuccessCode.java
  omocha-infra/src/main/java/org/omocha/infra/AuctionReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/ChatReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/ChatStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/common/util/PageSortImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ChatRepository.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ChatRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ChatRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ChatRoomRepository.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ChatRoomRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ChatRoomRepositoryImpl.java
Labels: 🥲 Refactor, 🐝 BE

#157 [FEAT] Auction Entity에 nowPrice, bidCount 속성 추가
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/BidDto.java
  omocha-domain/src/main/java/org/omocha/domain/auction/Auction.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/BidReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/HighestBidManager.java
  omocha-infra/src/main/java/org/omocha/infra/BidReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/BidStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/BidRepositoryImpl.java
Labels: 🐝 BE, 🐥 Feat

#174 [REFACTOR] ConcludeServiceImpl @Override 누락 추가
  omocha-domain/src/main/java/org/omocha/domain/auction/conclude/ConcludeService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/conclude/ConcludeServiceImpl.java
Labels: 🥲 Refactor, 🐝 BE

#176 [REFACTOR] Code Convention, Chatroom, Fields 수정
  build.gradle
  omocha-api/src/main/java/org/omocha/api/application/AuctionFacade.java
  omocha-api/src/main/java/org/omocha/api/application/ChatFacade.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuctionApi.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuctionController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/ChatController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/ChatRoomApi.java
  omocha-api/src/main/java/org/omocha/api/interfaces/ChatRoomController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/AuctionDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/AuctionDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/ChatDtoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/Auction.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionImagesFactory.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/BidReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatInfoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/conclude/ConcludeServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/exception/AuctionHasBidException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/AuctionImageDeleteFailException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/AuctionNotFoundException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/MemberInvalidException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/BidCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ChatCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ImageCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/JwtCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/OauthCode.java
  omocha-domain/src/main/java/org/omocha/domain/image/ImageCommand.java
  omocha-infra/src/main/java/org/omocha/infra/AuctionImagesFactoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/AuctionReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/ChatReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AuctionRepository.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AuctionRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AuctionRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ChatRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ChatRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ChatRoomRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ChatRoomRepositoryImpl.java
Labels: 🥲 Refactor, 🐝 BE, 🐥 Feat

#177 [REFACTOR] 변경된 컨벤션 적용
  omocha-api/src/main/java/org/omocha/api/application/BidFacade.java
  omocha-api/src/main/java/org/omocha/api/interfaces/BidController.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/BidService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/BidServiceImpl.java
Labels: 🥲 Refactor, 🐝 BE

#178 [REFACTOR] v2 기반 리팩토링 진행
  build.gradle
  omocha-api/build.gradle
  omocha-api/src/main/java/org/omocha/api/application/AuctionFacade.java
  omocha-api/src/main/java/org/omocha/api/application/BidFacade.java
  omocha-api/src/main/java/org/omocha/api/application/ChatFacade.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuctionApi.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuctionController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/BidController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/ChatController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/ChatRoomApi.java
  omocha-api/src/main/java/org/omocha/api/interfaces/ChatRoomController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/AuctionDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/AuctionDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/ChatDtoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/Auction.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionImagesFactory.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/BidReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/BidService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/BidServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatInfoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/conclude/ConcludeService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/conclude/ConcludeServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/exception/AuctionHasBidException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/AuctionImageDeleteFailException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/AuctionNotFoundException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/MemberInvalidException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/BidCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ChatCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ImageCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/JwtCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/OauthCode.java
  omocha-domain/src/main/java/org/omocha/domain/image/ImageCommand.java
  omocha-infra/src/main/java/org/omocha/infra/AuctionImagesFactoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/AuctionReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/ChatReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AuctionRepository.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AuctionRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AuctionRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ChatRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ChatRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ChatRoomRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ChatRoomRepositoryImpl.java
Labels: 🥲 Refactor, 🐝 BE

#181 [FEAT] 개발서버, 운영서버 환경 분리
  .github/workflows/deploy-CICD.yml
  Dockerfile
  docker-compose.yaml
  omocha-api/src/main/java/org/omocha/api/common/config/CustomCorsConfig.java
  omocha-api/src/main/java/org/omocha/api/common/config/SwaggerConfig.java
  omocha-api/src/main/java/org/omocha/api/interfaces/HealthCheckController.java
  omocha-api/src/main/resources/application.yml
  omocha-api/src/main/resources/logback-spring-dev.xml
Labels: 🐝 BE, 🐥 Feat

#168 [REFACTOR] QnA 리팩토링
  omocha-api/src/main/java/org/omocha/api/application/QnaFacade.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AnswerController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/QuestionController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/AnswerDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/QuestionDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/AnswerDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/QuestionDtoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/.keep
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/Answer.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/AnswerCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/AnswerInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/AnswerService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/AnswerServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/AnswerValidator.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/AnswerValidatorImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/Qna.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/QnaReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/QnaStore.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/Question.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/QuestionCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/QuestionInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/QuestionService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/QuestionServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/QuestionValidator.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/QuestionValidatorImpl.java
  omocha-domain/src/main/java/org/omocha/domain/exception/AnswerAlreadyExistException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/AnswerNotAllowedException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/AnswerNotFoundException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/QnaException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/QuestionNotAllowedException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/QuestionNotFoundException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ErrorCode.java
  omocha-infra/src/main/java/org/omocha/infra/QnaReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/QnaStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AnswerRepository.java
  omocha-infra/src/main/java/org/omocha/infra/repository/QuestionRepository.java
  omocha-infra/src/main/java/org/omocha/infra/repository/QuestionRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/QuestionRepositoryImpl.java
Labels: 🥲 Refactor, 🐝 BE

#183 [FEAT] Member Entity에 AverageRating 컬럼 추가
  omocha-api/src/main/java/org/omocha/api/common/auth/oauth/CustomOAuth2UserService.java
  omocha-api/src/main/java/org/omocha/api/common/auth/oauth/OAuth2UserInfo.java
  omocha-api/src/main/java/org/omocha/api/common/filter/JwtAuthFilter.java
  omocha-api/src/main/java/org/omocha/api/common/handler/OAuth2SuccessHandler.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/BidServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/conclude/ConcludeReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/conclude/ConcludeServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/Rating.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/RatingDbConverter.java
  omocha-domain/src/main/java/org/omocha/domain/exception/InvalidRatingException.java
  omocha-domain/src/main/java/org/omocha/domain/member/Member.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberCommand.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberReader.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/mypage/MypageServiceImpl.java
  omocha-infra/src/main/java/org/omocha/infra/ConcludeReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/MemberReaderImpl.java
Labels: 🥲 Refactor, 🐝 BE, 🐥 Feat

#151 [REFACTOR] Mypage 리팩토링
  omocha-api/src/main/java/org/omocha/api/application/MemberFacade.java
  omocha-api/src/main/java/org/omocha/api/application/MypageFacade.java
  omocha-api/src/main/java/org/omocha/api/common/auth/jwt/JwtGenerator.java
  omocha-api/src/main/java/org/omocha/api/common/auth/oauth/CustomOAuth2UserService.java
  omocha-api/src/main/java/org/omocha/api/common/filter/JwtAuthFilter.java
  omocha-api/src/main/java/org/omocha/api/common/util/PasswordManager.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuthController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/MypageController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/MemberDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/MypageDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/MemberDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/MypageDtoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/BidServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/chat/ChatServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/AnswerServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/QuestionServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/MypageCode.java
  omocha-domain/src/main/java/org/omocha/domain/member/Member.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberCommand.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberInfo.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberReader.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberService.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberValidator.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberValidatorImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/mypage/MypageInfo.java
  omocha-domain/src/main/java/org/omocha/domain/member/mypage/MypageService.java
  omocha-domain/src/main/java/org/omocha/domain/member/mypage/MypageServiceImpl.java
  omocha-infra/src/main/java/org/omocha/infra/MemberReaderImpl.java
Labels: 🥲 Refactor, 🐝 BE

#185 [REFACTOR] v2 기반 리팩토링 진행 ( Mypage )
  .github/workflows/deploy-CICD.yml
  Dockerfile
  docker-compose.yaml
  omocha-api/src/main/java/org/omocha/api/application/MemberFacade.java
  omocha-api/src/main/java/org/omocha/api/application/MypageFacade.java
  omocha-api/src/main/java/org/omocha/api/common/auth/jwt/JwtGenerator.java
  omocha-api/src/main/java/org/omocha/api/common/util/PasswordManager.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuthController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/MypageController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/MemberDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/MypageDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/MemberDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/MypageDtoMapper.java
  omocha-api/src/main/resources/application.yml
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/AnswerServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/QuestionServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/MypageCode.java
  omocha-domain/src/main/java/org/omocha/domain/member/Member.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberCommand.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberInfo.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberService.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberValidator.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberValidatorImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/mypage/MypageInfo.java
  omocha-domain/src/main/java/org/omocha/domain/member/mypage/MypageService.java
  omocha-domain/src/main/java/org/omocha/domain/member/mypage/MypageServiceImpl.java
Labels: 🥲 Refactor, 🐝 BE

#188 [FEAT] 리뷰 및 평점 관련 API 추가
  .github/workflows/deploy-CICD.yml
  Dockerfile
  docker-compose.yaml
  omocha-api/src/main/java/org/omocha/api/application/ReviewFacade.java
  omocha-api/src/main/java/org/omocha/api/common/auth/oauth/OAuth2UserInfo.java
  omocha-api/src/main/java/org/omocha/api/common/config/SecurityConfig.java
  omocha-api/src/main/java/org/omocha/api/interfaces/ReviewApi.java
  omocha-api/src/main/java/org/omocha/api/interfaces/ReviewController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/ReviewDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/ReviewDtoMapper.java
  omocha-api/src/main/resources/application.yml
  omocha-domain/src/main/java/org/omocha/domain/auction/Auction.java
  omocha-domain/src/main/java/org/omocha/domain/auction/conclude/Conclude.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/RatingDbConverter.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/Review.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/ReviewCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/ReviewInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/ReviewReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/ReviewService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/ReviewServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/ReviewStore.java
  omocha-domain/src/main/java/org/omocha/domain/exception/AuctionNotConcludedException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/ReviewAlreadyExistException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/ReviewException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/ReviewPermissionDeniedException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/SuccessCode.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberCommand.java
  omocha-infra/src/main/java/org/omocha/infra/ReviewReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/ReviewStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ReviewRepository.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ReviewRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ReviewRepositoryImpl.java
Labels: 🐝 BE, 🐥 Feat

#192 [FIX] getQuestion 수정
  omocha-domain/src/main/java/org/omocha/domain/auction/qna/AnswerServiceImpl.java
Labels: 🔧 Fix, 🐝 BE

#190 [FEAT] Category 구현
  .github/workflows/prod-CICD.yml
  .github/workflows/staging-CICD.yml
  omocha-api/src/main/java/org/omocha/api/application/CategoryFacade.java
  omocha-api/src/main/java/org/omocha/api/common/config/SecurityConfig.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuctionApi.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuctionController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/CategoryController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/AuctionDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/CategoryDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/AuctionDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/CategoryDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/CategoryMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/Auction.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionCategory.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/Category.java
  omocha-domain/src/main/java/org/omocha/domain/auction/CategoryCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/CategoryInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/CategoryReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/CategoryService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/CategoryServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/CategoryStore.java
  omocha-domain/src/main/java/org/omocha/domain/exception/CategoryNotFoundException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ErrorCode.java
  omocha-infra/src/main/java/org/omocha/infra/AuctionReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/CategoryReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/CategoryStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AuctionRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AuctionRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/CategoryRepository.java
  omocha-infra/src/main/java/org/omocha/infra/repository/CategoryRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/CategoryRepositoryImpl.java
Labels: 🐝 BE, 🐥 Feat

#195 [FIX] ErrorCode 중복 제거
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ErrorCode.java
Labels: 🔧 Fix, 🐝 BE

#197 [REFACTOR] : member ErrorCode 추가
  omocha-api/src/main/java/org/omocha/api/application/MemberFacade.java
  omocha-api/src/main/java/org/omocha/api/application/MypageFacade.java
  omocha-api/src/main/java/org/omocha/api/common/config/CustomCorsConfig.java
  omocha-api/src/main/java/org/omocha/api/common/util/PasswordManager.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuthController.java
  omocha-domain/src/main/java/org/omocha/domain/exception/MemberAlreadyExistException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/MemberException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/MemberInvalidMemberException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/MemberInvalidPasswordException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/MemberNotFoundExceptionForEmail.java
  omocha-domain/src/main/java/org/omocha/domain/exception/MemberNotFoundExceptionForId.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/MemberCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/SuccessCode.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberValidatorImpl.java
  omocha-infra/src/main/java/org/omocha/infra/MemberReaderImpl.java
Labels: 🥲 Refactor, 🐝 BE

#200 [FIX] 경매 상세조회 시 발생한 오류 해결
  omocha-api/src/main/java/org/omocha/api/interfaces/AuctionController.java
Labels: 🔧 Fix, 🐝 BE

#209 [FEAT] 찜 기능 구현 및 url path 수정
  omocha-api/src/main/java/org/omocha/api/application/AuctionFacade.java
  omocha-api/src/main/java/org/omocha/api/application/ChatFacade.java
  omocha-api/src/main/java/org/omocha/api/common/config/SecurityConfig.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuctionApi.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuctionController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/ChatRoomController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/AuctionDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/AuctionDtoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/Auction.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/LikeReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/LikeStore.java
  omocha-domain/src/main/java/org/omocha/domain/auction/Likes.java
  omocha-domain/src/main/java/org/omocha/domain/exception/LikeCountNegativeException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/SuccessCode.java
  omocha-infra/src/main/java/org/omocha/infra/AuctionReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/AuctionStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/LikeReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/LikeStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AuctionRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ChatRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/LikeRepository.java
  omocha-infra/src/main/java/org/omocha/infra/repository/LikeRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/LikeRepositoryImpl.java
Labels: 🐝 BE, 🐥 Feat

#206 [FEAT] 리뷰 조회 API 분리
  omocha-api/src/main/java/org/omocha/api/application/ReviewFacade.java
  omocha-api/src/main/java/org/omocha/api/common/config/SecurityConfig.java
  omocha-api/src/main/java/org/omocha/api/interfaces/ReviewApi.java
  omocha-api/src/main/java/org/omocha/api/interfaces/ReviewController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/ReviewDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/ReviewDtoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/Review.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/ReviewCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/ReviewInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/ReviewReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/ReviewService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/review/ReviewServiceImpl.java
  omocha-infra/src/main/java/org/omocha/infra/ReviewReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ReviewRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/ReviewRepositoryImpl.java
Labels: 🐝 BE, 🐥 Feat

#210 [FEAT] 즉시구매 API 추가
  omocha-api/src/main/java/org/omocha/api/application/BidFacade.java
  omocha-api/src/main/java/org/omocha/api/interfaces/BidApi.java
  omocha-api/src/main/java/org/omocha/api/interfaces/BidController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/AuctionDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/BidDtoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/Auction.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/BidCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/BidService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/BidServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/BidValidator.java
  omocha-domain/src/main/java/org/omocha/domain/auction/bid/BidValidatorImpl.java
  omocha-domain/src/main/java/org/omocha/domain/exception/BidExceedsInstantBuyException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/SelfBidNotAllowedException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/SuccessCode.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AuctionRepositoryImpl.java
Labels: 🐝 BE, 🐥 Feat

#222 [REFACTOR] Auth Swagger용 Api 추가
  omocha-api/src/main/java/org/omocha/api/interfaces/AuthApi.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuthController.java
Labels: 🥲 Refactor, 🐝 BE

#223 [REFACTOR] QnA Swagger 추가
  omocha-api/src/main/java/org/omocha/api/interfaces/AnswerApi.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AnswerController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/QuestionApi.java
  omocha-api/src/main/java/org/omocha/api/interfaces/QuestionController.java
Labels: 🥲 Refactor, 🐝 BE

#226 [REFACTOR]: QnA Exception 변경
  omocha-api/src/main/java/org/omocha/api/qna/AnswerController.java
  omocha-api/src/main/java/org/omocha/api/qna/QuestionController.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/exception/AuctionOwnerMismatchException.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/SuccessCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/BidCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ChatCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/ImageCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/JwtCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/OauthCode.java
  omocha-domain/src/main/java/org/omocha/domain/exception/code/QnACode.java
  omocha-domain/src/main/java/org/omocha/domain/member/exception/MemberInvalidException.java
  omocha-domain/src/main/java/org/omocha/domain/member/exception/MemberInvalidMemberException.java
  omocha-domain/src/main/java/org/omocha/domain/qna/answer/AnswerValidatorImpl.java
Labels: 🥲 Refactor, 🐝 BE

#227 [REFACTOR] memberId 관련 컬럼명 변경
  omocha-api/src/main/java/org/omocha/api/bid/BidController.java
  omocha-api/src/main/java/org/omocha/api/bid/dto/BidDto.java
  omocha-api/src/main/java/org/omocha/api/bid/dto/BidDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/chat/ChatRoomController.java
  omocha-api/src/main/java/org/omocha/api/chat/dto/ChatDto.java
  omocha-api/src/main/java/org/omocha/api/chat/dto/ChatDtoMapper.java
  omocha-api/src/main/resources/application.yml
  omocha-domain/src/main/java/org/omocha/domain/bid/Bid.java
  omocha-domain/src/main/java/org/omocha/domain/bid/BidCommand.java
  omocha-domain/src/main/java/org/omocha/domain/bid/BidInfo.java
  omocha-domain/src/main/java/org/omocha/domain/bid/BidServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/bid/validate/BidValidator.java
  omocha-domain/src/main/java/org/omocha/domain/bid/validate/BidValidatorImpl.java
  omocha-domain/src/main/java/org/omocha/domain/chat/Chat.java
  omocha-domain/src/main/java/org/omocha/domain/chat/ChatCommand.java
  omocha-domain/src/main/java/org/omocha/domain/chat/ChatInfo.java
  omocha-domain/src/main/java/org/omocha/domain/chat/ChatRoom.java
  omocha-domain/src/main/java/org/omocha/domain/chat/ChatServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/conclude/Conclude.java
  omocha-domain/src/main/java/org/omocha/domain/review/Review.java
  omocha-domain/src/main/java/org/omocha/domain/review/ReviewServiceImpl.java
  omocha-infra/src/main/java/org/omocha/infra/chat/repository/ChatRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/chat/repository/ChatRoomRepositoryImpl.java
Labels: 🥲 Refactor, 🐝 BE

#233 [FEAT] Random Nickname 생성 & memberId (details)에서 삭제
  omocha-api/src/main/java/org/omocha/api/auction/AuctionApi.java
  omocha-api/src/main/java/org/omocha/api/auction/AuctionController.java
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/common/config/SecurityConfig.java
  omocha-api/src/main/java/org/omocha/api/common/handler/GlobalExceptionHandler.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionStore.java
  omocha-domain/src/main/java/org/omocha/domain/auction/exception/AuctionException.java
  omocha-domain/src/main/java/org/omocha/domain/category/exception/CategoryNotFoundException.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberCommand.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/RandomNickNameGenerator.java
  omocha-infra/src/main/java/org/omocha/infra/auction/AuctionReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/auction/AuctionStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/category/CategoryReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/category/CategoryStoreImpl.java
Labels: 🐝 BE, 🐥 Feat

#231 [REFACTOR] 리뷰 확인 쿼리 추가
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDto.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfo.java
  omocha-infra/src/main/java/org/omocha/infra/auction/repository/AuctionRepositoryImpl.java
Labels: 🥲 Refactor, 🐝 BE

#234 [FEAT] 유저 로그인 타입 + 찜 개수 조회 + 즉시 구매 required false 변경
  build.gradle
  omocha-api/src/main/java/org/omocha/api/auction/AuctionApi.java
  omocha-api/src/main/java/org/omocha/api/auction/AuctionController.java
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDto.java
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/member/dto/MemberDto.java
  omocha-api/src/main/resources/application.yml
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfo.java
  omocha-domain/src/main/java/org/omocha/domain/bid/validate/BidValidatorImpl.java
  omocha-domain/src/main/java/org/omocha/domain/likes/LikeReader.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberInfo.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
  omocha-infra/src/main/java/org/omocha/infra/auction/repository/AuctionRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/likes/LikeReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/likes/repository/LikeRepository.java
Labels: 🔧 Fix, 🐝 BE, 🐥 Feat

#238 [FIX] build 에러 수정
  omocha-api/src/main/java/org/omocha/api/auction/AuctionApi.java
  omocha-api/src/main/java/org/omocha/api/auction/AuctionController.java
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDto.java
Labels: 🐝 BE, 🐥 Feat

#244 [FEAT] Exception 처리 (Auction Image)
  omocha-api/src/main/java/org/omocha/api/common/handler/GlobalExceptionHandler.java
  omocha-domain/src/main/java/org/omocha/domain/auction/exception/AuctionHasBidException.java
  omocha-domain/src/main/java/org/omocha/domain/auction/exception/AuctionImageDeleteFailException.java
  omocha-domain/src/main/java/org/omocha/domain/auction/exception/AuctionImageNotFoundException.java
  omocha-domain/src/main/java/org/omocha/domain/auction/exception/AuctionNotFoundException.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/image/exception/ImageDeleteFailException.java
  omocha-domain/src/main/java/org/omocha/domain/image/exception/ImageException.java
  omocha-domain/src/main/java/org/omocha/domain/image/exception/ImageUploadFailException.java
  omocha-domain/src/main/java/org/omocha/domain/image/exception/ImageWrongFileNameException.java
  omocha-infra/src/main/java/org/omocha/infra/image/S3Provider.java
Labels: 🐝 BE, 🐥 Feat

#251 [FEAT] 비밀번호 변경 시 검증 로직 추가
  omocha-api/src/main/java/org/omocha/api/common/util/PasswordManager.java
  omocha-api/src/main/java/org/omocha/api/member/MemberController.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/member/exception/MemberIdenticalPassword.java
Labels: 🥲 Refactor, 🐝 BE

#253 [FEAT] OAuth 회원가입 시 랜덤 닉네임 생성
  omocha-api/src/main/java/org/omocha/api/auth/oauth/CustomOAuth2UserService.java
  omocha-api/src/main/java/org/omocha/api/auth/oauth/OAuth2UserInfo.java
  omocha-api/src/main/resources/static/favicon.ico
  omocha-domain/src/main/java/org/omocha/domain/member/MemberCommand.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
Labels: 🥲 Refactor, 🐝 BE, 🐥 Feat

#255 [FEAT] 상대방 정보 조회
  omocha-api/src/main/java/org/omocha/api/auction/AuctionApi.java
  omocha-api/src/main/java/org/omocha/api/auction/AuctionController.java
  omocha-api/src/main/java/org/omocha/api/auction/AuctionFacade.java
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDto.java
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/common/config/SecurityConfig.java
  omocha-api/src/main/java/org/omocha/api/member/MemberApi.java
  omocha-api/src/main/java/org/omocha/api/member/MemberController.java
  omocha-api/src/main/java/org/omocha/api/member/MemberFacade.java
  omocha-api/src/main/java/org/omocha/api/member/dto/MemberDto.java
  omocha-api/src/main/java/org/omocha/api/member/dto/MemberDtoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/SuccessCode.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberCommand.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberInfo.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberService.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
  omocha-infra/src/main/java/org/omocha/infra/auction/AuctionReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/auction/repository/AuctionRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/auction/repository/AuctionRepositoryImpl.java
Labels: 🐝 BE, 🐥 Feat

#254 [REFACTOR] 일반 회원 정보 변경 시 birth 누락 추가
  omocha-api/src/main/java/org/omocha/api/member/MemberApi.java
  omocha-api/src/main/java/org/omocha/api/member/dto/MemberDto.java
  omocha-domain/src/main/java/org/omocha/domain/member/Member.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberCommand.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberInfo.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/vo/PhoneNumber.java
Labels: 🥲 Refactor, 🐝 BE

#261 [FIX] Chatting Message JsonFormat 추가
  omocha-domain/src/main/java/org/omocha/domain/chat/ChatInfo.java
Labels: 🔧 Fix, 🐝 BE

#262 [REFACTOR] Refresh Token이 올바르지 않을 경우 쿠키 삭제 + Exception 리팩토링
  omocha-api/build.gradle
  omocha-api/src/main/java/org/omocha/api/auth/AuthController.java
  omocha-api/src/main/java/org/omocha/api/auth/jwt/JwtProvider.java
  omocha-api/src/main/java/org/omocha/api/auth/jwt/JwtUtil.java
  omocha-api/src/main/java/org/omocha/api/auth/jwt/RefreshTokenManager.java
  omocha-api/src/main/java/org/omocha/api/common/filter/JwtAuthFilter.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAccessDeniedHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAuthenticationEntryPointHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/GlobalExceptionHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/OAuth2FailureHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/OAuth2SuccessHandler.java
  omocha-api/src/main/resources/application.yml
  omocha-domain/src/main/java/org/omocha/domain/auction/exception/AuctionException.java
  omocha-domain/src/main/java/org/omocha/domain/auction/exception/PriceTooHighException.java
  omocha-domain/src/main/java/org/omocha/domain/bid/exception/BidException.java
  omocha-domain/src/main/java/org/omocha/domain/chat/exception/ChatException.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/common/exception/OmochaException.java
  omocha-domain/src/main/java/org/omocha/domain/image/exception/ImageException.java
  omocha-domain/src/main/java/org/omocha/domain/member/exception/MemberException.java
  omocha-domain/src/main/java/org/omocha/domain/member/exception/jwt/InvalidRefreshTokenException.java
  omocha-domain/src/main/java/org/omocha/domain/member/exception/oauth/OauthException.java
  omocha-domain/src/main/java/org/omocha/domain/qna/exception/QnaException.java
  omocha-domain/src/main/java/org/omocha/domain/review/exception/ReviewException.java
Labels: 🥲 Refactor, 🐝 BE

#267 [FIX] addAuction 검증 코드 추가
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/auction/exception/AuctionBidUnitTooHighException.java
  omocha-domain/src/main/java/org/omocha/domain/auction/exception/AuctionEndDateBeforeNowException.java
  omocha-domain/src/main/java/org/omocha/domain/auction/exception/AuctionStartPriceHigherInstantBuyPriceException.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
  omocha-infra/src/main/java/org/omocha/infra/category/repository/CategoryRepository.java
Labels: 🔧 Fix, 🐝 BE

#268 [REFACTOR] logback 수정
  .gitignore
  omocha-api/src/main/java/org/omocha/api/common/CustomHighlightConverter.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAccessDeniedHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAuthenticationEntryPointHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/GlobalExceptionHandler.java
  omocha-api/src/main/java/org/omocha/api/common/util/P6SpySqlFormatter.java
  omocha-api/src/main/resources/logback-spring-dev.xml
  omocha-api/src/main/resources/logback-spring-local.xml
  omocha-api/src/main/resources/logback-spring-prod.xml
  omocha-api/src/main/resources/logback-spring.xml
Labels: 🥲 Refactor, 🐝 BE

#278 [FIX] QA 변경 사항 수정
  omocha-api/src/main/java/org/omocha/api/common/config/SecurityConfig.java
  omocha-api/src/main/java/org/omocha/api/common/handler/GlobalExceptionHandler.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionServiceImpl.java
Labels: 🔧 Fix, 🐝 BE

#275 [REFACTOR] Logback 경로 및 포맷 변경
  docker-compose.yaml
  omocha-api/src/main/java/org/omocha/api/common/handler/GlobalExceptionHandler.java
  omocha-api/src/main/resources/application.yml
  omocha-api/src/main/resources/logback-spring-dev.xml
  omocha-api/src/main/resources/logback-spring-local.xml
  omocha-api/src/main/resources/logback-spring-prod.xml
  omocha-api/src/main/resources/logback-spring.xml
Labels: 🥲 Refactor, 🐝 BE

#282 [FIX] Image 허용 최대값 예외 처리
  .gitignore
  omocha-api/src/main/java/org/omocha/api/common/handler/GlobalExceptionHandler.java
  omocha-api/src/main/resources/application.yml
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
Labels: 🔧 Fix, 🐝 BE

#281 [FIX] response에 member email, nickname 추가
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDto.java
  omocha-api/src/main/java/org/omocha/api/auth/AuthApi.java
  omocha-api/src/main/java/org/omocha/api/auth/AuthController.java
  omocha-api/src/main/java/org/omocha/api/bid/dto/BidDto.java
  omocha-api/src/main/java/org/omocha/api/qna/AnswerApi.java
  omocha-api/src/main/java/org/omocha/api/qna/AnswerController.java
  omocha-api/src/main/java/org/omocha/api/qna/QuestionApi.java
  omocha-api/src/main/java/org/omocha/api/qna/QuestionController.java
  omocha-api/src/main/java/org/omocha/api/review/dto/ReviewDto.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/bid/BidInfo.java
Labels: 🔧 Fix, 🐝 BE

#284 [FIX] Request Json 역직렬화 에러처리
  omocha-api/src/main/java/org/omocha/api/common/handler/GlobalExceptionHandler.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
Labels: 🔧 Fix, 🐝 BE

#286 [FIX] Request에 NotNull 체크용 @Valid 추가
  build.gradle
  omocha-api/build.gradle
  omocha-api/src/main/java/org/omocha/api/auction/AuctionController.java
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDto.java
  omocha-api/src/main/java/org/omocha/api/auth/dto/AuthDto.java
  omocha-api/src/main/java/org/omocha/api/bid/BidController.java
  omocha-api/src/main/java/org/omocha/api/bid/dto/BidDto.java
  omocha-api/src/main/java/org/omocha/api/category/CategoryController.java
  omocha-api/src/main/java/org/omocha/api/category/dto/CategoryDto.java
  omocha-api/src/main/java/org/omocha/api/chat/dto/ChatDto.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAccessDeniedHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAuthenticationEntryPointHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/GlobalExceptionHandler.java
  omocha-api/src/main/java/org/omocha/api/member/MemberController.java
  omocha-api/src/main/java/org/omocha/api/member/dto/MemberDto.java
  omocha-api/src/main/java/org/omocha/api/qna/AnswerController.java
  omocha-api/src/main/java/org/omocha/api/qna/dto/AnswerDto.java
  omocha-api/src/main/java/org/omocha/api/qna/dto/QuestionDto.java
  omocha-api/src/main/java/org/omocha/api/review/dto/ReviewDto.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
Labels: 🔧 Fix, 🐝 BE

#289 [FIX] Domain 노출 수정 및 Logback 변경
  omocha-api/src/main/java/org/omocha/api/auth/jwt/JwtUtil.java
  omocha-api/src/main/java/org/omocha/api/common/config/CustomCorsConfig.java
  omocha-api/src/main/java/org/omocha/api/common/config/SwaggerConfig.java
  omocha-api/src/main/java/org/omocha/api/common/handler/GlobalExceptionHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/OAuth2FailureHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/OAuth2SuccessHandler.java
  omocha-api/src/main/resources/application.yml
  omocha-api/src/main/resources/logback-spring-dev.xml
  omocha-api/src/main/resources/logback-spring-local.xml
  omocha-api/src/main/resources/logback-spring-prod.xml
  omocha-api/src/main/resources/logback-spring.xml
  omocha-domain/src/main/java/org/omocha/domain/common/config/WebSocketConfig.java
Labels: 🔧 Fix, 🥲 Refactor, 🐝 BE

#290 [FEAT] test code 작성
  .gitignore
  build.gradle
  omocha-api/build.gradle
  omocha-api/src/main/java/org/omocha/api/common/util/P6SpySqlFormatter.java
  omocha-api/src/test/java/org/omocha/api/auction/AuctionAddTest.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionCommand.java
  omocha-infra/src/main/java/org/omocha/infra/auction/AuctionStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/auction/repository/AuctionRepositoryImpl.java
Labels: 🐝 BE, 🐥 Feat

#291 [REFACTOR] nickname 컨벤션에 맞게 수정
  omocha-api/src/main/java/org/omocha/api/auth/oauth/CustomOAuth2UserService.java
  omocha-api/src/main/java/org/omocha/api/member/dto/MemberDto.java
  omocha-api/src/main/java/org/omocha/api/qna/dto/QuestionDto.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberCommand.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberInfo.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberReader.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/RandomNicknameGenerator.java
  omocha-domain/src/main/java/org/omocha/domain/member/exception/MemberNickNameDuplicateException.java
  omocha-domain/src/main/java/org/omocha/domain/member/exception/MemberNicknameDuplicateException.java
  omocha-domain/src/main/java/org/omocha/domain/member/validate/MemberValidator.java
  omocha-domain/src/main/java/org/omocha/domain/member/validate/MemberValidatorImpl.java
  omocha-domain/src/main/java/org/omocha/domain/qna/question/QuestionInfo.java
  omocha-infra/src/main/java/org/omocha/infra/member/MemberReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/member/repository/MemberRepository.java
Labels: 🥲 Refactor, 🐝 BE

#295 [FIX] 이미지 저장 수정
  omocha-api/src/main/java/org/omocha/api/auction/AuctionApi.java
  omocha-api/src/main/java/org/omocha/api/auction/AuctionController.java
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDtoMapper.java
  omocha-api/src/test/java/org/omocha/api/auction/AuctionAddTest.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionCommand.java
  omocha-infra/src/main/java/org/omocha/infra/image/AuctionImagesFactoryImpl.java
Labels: 🔧 Fix, 🐝 BE

#297 [FIX] category 수정 및 flyway 적용
  omocha-api/build.gradle
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDto.java
  omocha-api/src/main/resources/application.yml
  omocha-api/src/main/resources/db/migration/V1.0.1__init.sql
  omocha-api/src/main/resources/db/migration/V1.0.2__rename_foreign_keys.sql
  omocha-api/src/main/resources/db/migration/V1.0.3__update_category_and_auction.sql
  omocha-api/src/test/java/org/omocha/api/auction/AuctionAddTest.java
  omocha-domain/src/main/java/org/omocha/domain/auction/Auction.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/category/AuctionCategory.java
  omocha-domain/src/main/java/org/omocha/domain/category/Category.java
  omocha-domain/src/main/java/org/omocha/domain/category/CategoryInfo.java
  omocha-domain/src/main/java/org/omocha/domain/category/CategoryStore.java
  omocha-domain/src/main/java/org/omocha/domain/qna/question/Question.java
  omocha-infra/src/main/java/org/omocha/infra/auction/repository/AuctionRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/category/CategoryReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/category/CategoryStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/category/repository/CategoryRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/likes/repository/LikeRepositoryImpl.java
Labels: 🔧 Fix, 🐝 BE, 🐥 Feat

#293 [FEAT] Mail 인증 추가
  omocha-api/src/main/java/org/omocha/api/common/config/SecurityConfig.java
  omocha-api/src/main/java/org/omocha/api/mail/MailApi.java
  omocha-api/src/main/java/org/omocha/api/mail/MailController.java
  omocha-api/src/main/java/org/omocha/api/mail/MailFacade.java
  omocha-api/src/main/java/org/omocha/api/mail/MailScheduler.java
  omocha-api/src/main/java/org/omocha/api/mail/dto/MailDto.java
  omocha-api/src/main/java/org/omocha/api/mail/dto/MailDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/member/dto/MemberDto.java
  omocha-api/src/main/resources/application.yml
  omocha-api/src/main/resources/db/migration/V1.1.1__update_member.sql
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/SuccessCode.java
  omocha-domain/src/main/java/org/omocha/domain/mail/AuthCode.java
  omocha-domain/src/main/java/org/omocha/domain/mail/CodeManager.java
  omocha-domain/src/main/java/org/omocha/domain/mail/MailCommand.java
  omocha-domain/src/main/java/org/omocha/domain/mail/MailSender.java
  omocha-domain/src/main/java/org/omocha/domain/mail/MailService.java
  omocha-domain/src/main/java/org/omocha/domain/mail/MailServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/mail/exception/MailCodeKeyNotFoundException.java
  omocha-domain/src/main/java/org/omocha/domain/mail/exception/MailException.java
  omocha-domain/src/main/java/org/omocha/domain/mail/exception/MailSendFailException.java
  omocha-domain/src/main/java/org/omocha/domain/member/Member.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberCommand.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberInfo.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
  omocha-infra/build.gradle
  omocha-infra/src/main/java/org/omocha/infra/mail/MailSenderImpl.java
Labels: 🐝 BE, 🐥 Feat
