Repository Kernel360/F2-omocha-BE, pull requests merged in 2024-12, with the labels that each got.

#299 [FEAT] Password VO 추가
  omocha-api/src/main/java/org/omocha/api/auth/AuthController.java
  omocha-api/src/main/java/org/omocha/api/auth/AuthFacade.java
  omocha-api/src/main/java/org/omocha/api/auth/dto/AuthDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/auth/jwt/UserPrincipal.java
  omocha-api/src/main/java/org/omocha/api/common/util/PasswordManager.java
  omocha-api/src/main/java/org/omocha/api/common/util/ValueObjectMapper.java
  omocha-api/src/main/java/org/omocha/api/member/MemberController.java
  omocha-api/src/main/java/org/omocha/api/member/MemberFacade.java
  omocha-api/src/main/java/org/omocha/api/member/dto/MemberDtoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/member/Member.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberCommand.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberInfo.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/vo/Email.java
  omocha-domain/src/main/java/org/omocha/domain/member/vo/Password.java
  omocha-domain/src/main/java/org/omocha/domain/member/vo/PasswordDbConverter.java
Labels: 🐝 BE, 🐥 Feat

#302 [FEAT] s3이미지 업로드/삭제 API 구현
  omocha-api/src/main/java/org/omocha/api/image/ImageApi.java
  omocha-api/src/main/java/org/omocha/api/image/ImageController.java
  omocha-api/src/main/java/org/omocha/api/image/ImageFacade.java
  omocha-api/src/main/java/org/omocha/api/image/dto/ImageDto.java
  omocha-api/src/main/java/org/omocha/api/image/dto/ImageDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/member/MemberFacade.java
  omocha-domain/src/main/java/org/omocha/domain/auction/Auction.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/SuccessCode.java
  omocha-domain/src/main/java/org/omocha/domain/image/Image.java
  omocha-domain/src/main/java/org/omocha/domain/image/ImageCommand.java
  omocha-domain/src/main/java/org/omocha/domain/image/ImageInfo.java
  omocha-domain/src/main/java/org/omocha/domain/image/ImageReader.java
  omocha-domain/src/main/java/org/omocha/domain/image/ImageService.java
  omocha-domain/src/main/java/org/omocha/domain/image/ImageStore.java
  omocha-domain/src/main/java/org/omocha/domain/image/exception/ImageNotFoundException.java
  omocha-infra/src/main/java/org/omocha/infra/auction/AuctionReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/image/AuctionImagesFactoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/image/ImageReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/image/ImageServiceImpl.java
  omocha-infra/src/main/java/org/omocha/infra/image/ImageStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/image/repository/ImageRepository.java
  omocha-infra/src/main/java/org/omocha/infra/likes/repository/LikeRepositoryImpl.java
Labels: 🐝 BE, 🐥 Feat

#303 [FIX] 로그인 인증/인가 방식 쿠키 => 헤더로 변경
  omocha-api/src/main/java/org/omocha/api/auth/AuthApi.java
  omocha-api/src/main/java/org/omocha/api/auth/AuthController.java
  omocha-api/src/main/java/org/omocha/api/auth/AuthFacade.java
  omocha-api/src/main/java/org/omocha/api/auth/dto/AuthDto.java
  omocha-api/src/main/java/org/omocha/api/auth/dto/AuthDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/auth/jwt/JwtGenerator.java
  omocha-api/src/main/java/org/omocha/api/auth/jwt/JwtProvider.java
  omocha-api/src/main/java/org/omocha/api/auth/jwt/JwtUtil.java
  omocha-api/src/main/java/org/omocha/api/auth/oauth/OAuth2UserInfo.java
  omocha-api/src/main/java/org/omocha/api/common/config/SwaggerConfig.java
  omocha-api/src/main/java/org/omocha/api/common/filter/JwtAuthFilter.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAccessDeniedHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAuthenticationEntryPointHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/GlobalExceptionHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/OAuth2FailureHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/OAuth2SuccessHandler.java
  omocha-api/src/main/resources/application.yml
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/SuccessCode.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberCommand.java
  omocha-domain/src/main/java/org/omocha/domain/member/exception/InvalidRefreshTokenException.java
  omocha-domain/src/main/java/org/omocha/domain/member/exception/InvalidTokenOwnerException.java
  omocha-domain/src/main/java/org/omocha/domain/member/exception/UnsupportedOAuthProviderException.java
  omocha-domain/src/main/java/org/omocha/domain/member/exception/oauth/OauthException.java
Labels: 🔧 Fix, 🐝 BE

#305 [FIX] github 보안그룹 secret 수정
  .github/workflows/prod-CICD.yml
  .github/workflows/staging-CICD.yml
Labels: 🔧 Fix, 🐝 BE

#308 [FIX] github secret 롤백
  .github/workflows/prod-CICD.yml
  .github/workflows/staging-CICD.yml
Labels: 🔧 Fix, 🐝 BE

#312 [FIX] mail url path 수정
  omocha-api/src/main/java/org/omocha/api/mail/MailController.java
Labels: 🔧 Fix, 🐝 BE

#316 [FEAT] Redis 추가
  .github/workflows/staging-CICD.yml
  docker-compose.yaml
  omocha-api/src/main/java/org/omocha/api/mail/MailScheduler.java
  omocha-api/src/main/resources/application.yml
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/mail/AuthCode.java
  omocha-domain/src/main/java/org/omocha/domain/mail/CodeCacheReader.java
  omocha-domain/src/main/java/org/omocha/domain/mail/CodeCacheStore.java
  omocha-domain/src/main/java/org/omocha/domain/mail/CodeManager.java
  omocha-domain/src/main/java/org/omocha/domain/mail/MailService.java
  omocha-domain/src/main/java/org/omocha/domain/mail/MailServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/mail/exception/MailAuthCodeMisMachException.java
  omocha-domain/src/main/java/org/omocha/domain/mail/exception/MailCodeKeyNotFoundException.java
  omocha-infra/build.gradle
  omocha-infra/src/main/java/org/omocha/infra/common/RedisPrefix.java
  omocha-infra/src/main/java/org/omocha/infra/common/config/RedisConfig.java
  omocha-infra/src/main/java/org/omocha/infra/mail/CodeCacheReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/mail/CodeCacheStoreImpl.java
Labels: 🐝 BE, 🐥 Feat

#315 [REFACTOR] build.gradle 의존성 재조정
  build.gradle
  omocha-api/build.gradle
  omocha-api/src/test/java/org/omocha/api/auction/AuctionAddTest.java
  omocha-domain/build.gradle
  omocha-domain/src/main/java/org/omocha/domain/chat/ChatInfoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/chat/ChatMessageSender.java
  omocha-domain/src/main/java/org/omocha/domain/chat/ChatServiceImpl.java
  omocha-infra/build.gradle
  omocha-infra/src/main/java/org/omocha/infra/chat/ChatMessageSenderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/common/config/WebSocketConfig.java
Labels: 🥲 Refactor, 🐝 BE

#314 [FIX] 이미지 오류 해결 및 필요한 필드 추가
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDto.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfo.java
  omocha-infra/src/main/java/org/omocha/infra/auction/repository/AuctionRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/image/AuctionImagesFactoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/likes/repository/LikeRepositoryImpl.java
Labels: 🔧 Fix, 🐝 BE

#321 [REFACTOR] Token 관리 변경 [Redis]
  omocha-api/src/main/java/org/omocha/api/auth/jwt/JwtProvider.java
  omocha-api/src/main/java/org/omocha/api/auth/jwt/RefreshTokenManager.java
  omocha-infra/src/main/java/org/omocha/infra/auth/TokenCacheReader.java
  omocha-infra/src/main/java/org/omocha/infra/auth/TokenCacheReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/auth/TokenCacheStore.java
  omocha-infra/src/main/java/org/omocha/infra/auth/TokenCacheStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/auth/repository/TokenCacheRepository.java
  omocha-infra/src/main/java/org/omocha/infra/auth/repository/TokenCacheRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/auth/repository/TokenRepository.java
  omocha-infra/src/main/java/org/omocha/infra/common/RedisPrefix.java
Labels: 🥲 Refactor, 🐝 BE

#319 [FIX] OAuth 로그인 처리 방식 변경
  omocha-api/src/main/java/org/omocha/api/auth/oauth/CustomOAuth2UserService.java
  omocha-api/src/main/java/org/omocha/api/common/handler/OAuth2SuccessHandler.java
  omocha-api/src/main/resources/application.yml
Labels: 🔧 Fix, 🐝 BE

#325 [FIX] 경매 생성시 즉시구매 가능여부 반환
  omocha-api/src/main/java/org/omocha/api/auction/AuctionController.java
  omocha-api/src/main/java/org/omocha/api/auction/AuctionFacade.java
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDto.java
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDtoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionServiceImpl.java
Labels: 🔧 Fix, 🐝 BE

#327 [FIX] token repository 오류 수정
  omocha-infra/src/main/java/org/omocha/infra/auth/TokenCacheReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/auth/TokenCacheStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/auth/repository/TokenCacheRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/auth/repository/TokenRepository.java
Labels: 🔧 Fix, 🐝 BE

#331 [REFACTOR] 배포 redis 경로 수정
  .github/workflows/staging-CICD.yml
  docker-compose.yaml
Labels: 🥲 Refactor, 🐝 BE

#335 [FIX] OAuth 로그인 시 Provider도 함께 반환
  omocha-api/src/main/java/org/omocha/api/auth/jwt/UserPrincipal.java
  omocha-api/src/main/java/org/omocha/api/auth/oauth/CustomOAuth2UserService.java
  omocha-api/src/main/java/org/omocha/api/common/handler/OAuth2SuccessHandler.java
Labels: 🔧 Fix, 🐝 BE

#333 [Refactor] 프론트에서 요청한 수정사항
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDto.java
  omocha-api/src/main/java/org/omocha/api/common/config/SecurityConfig.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfo.java
  omocha-infra/src/main/java/org/omocha/infra/auction/repository/AuctionRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/image/AuctionImagesFactoryImpl.java
Labels: 🥲 Refactor, 🐝 BE

#329 [FEAT] 입찰 동시성 문제 처리
  build.gradle
  omocha-api/src/main/java/org/omocha/api/bid/BidApi.java
  omocha-api/src/test/java/org/omocha/api/bid/BidTest.java
  omocha-domain/src/main/java/org/omocha/domain/bid/BidServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/common/annotation/DistributedLock.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/common/exception/redis/LockInterruptedException.java
  omocha-domain/src/main/java/org/omocha/domain/common/exception/redis/RLockNotAvailableException.java
  omocha-infra/build.gradle
  omocha-infra/src/main/java/org/omocha/infra/common/RedisPrefix.java
  omocha-infra/src/main/java/org/omocha/infra/common/config/RedissonConfig.java
  omocha-infra/src/main/java/org/omocha/infra/common/redis/AopForTransaction.java
  omocha-infra/src/main/java/org/omocha/infra/common/redis/CustomSpringELParser.java
  omocha-infra/src/main/java/org/omocha/infra/common/redis/DistributedLockAop.java
Labels: 🐝 BE, 🐥 Feat

#337 [DEPLOY] 동시성 처리 후 배포
  .github/workflows/staging-CICD.yml
  build.gradle
  docker-compose.yaml
  omocha-api/src/main/java/org/omocha/api/auction/dto/AuctionDto.java
  omocha-api/src/main/java/org/omocha/api/auth/jwt/UserPrincipal.java
  omocha-api/src/main/java/org/omocha/api/auth/oauth/CustomOAuth2UserService.java
  omocha-api/src/main/java/org/omocha/api/bid/BidApi.java
  omocha-api/src/main/java/org/omocha/api/common/config/SecurityConfig.java
  omocha-api/src/main/java/org/omocha/api/common/handler/OAuth2SuccessHandler.java
  omocha-api/src/test/java/org/omocha/api/bid/BidTest.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfo.java
  omocha-domain/src/main/java/org/omocha/domain/bid/BidServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/common/annotation/DistributedLock.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/common/exception/redis/LockInterruptedException.java
  omocha-domain/src/main/java/org/omocha/domain/common/exception/redis/RLockNotAvailableException.java
  omocha-infra/build.gradle
  omocha-infra/src/main/java/org/omocha/infra/auction/repository/AuctionRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/common/RedisPrefix.java
  omocha-infra/src/main/java/org/omocha/infra/common/config/RedissonConfig.java
  omocha-infra/src/main/java/org/omocha/infra/common/redis/AopForTransaction.java
  omocha-infra/src/main/java/org/omocha/infra/common/redis/CustomSpringELParser.java
  omocha-infra/src/main/java/org/omocha/infra/common/redis/DistributedLockAop.java
  omocha-infra/src/main/java/org/omocha/infra/image/AuctionImagesFactoryImpl.java
Labels: 🐝 BE, deploy

#339 [FIX] MessageType Validation 수정
  omocha-api/src/main/java/org/omocha/api/chat/dto/ChatDto.java
  omocha-api/src/main/java/org/omocha/api/chat/dto/ChatDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/common/util/ValueObjectMapper.java
  omocha-api/src/test/java/org/omocha/api/bid/BidTest.java
Labels: 🔧 Fix, 🐝 BE

#349 [DOCS] Readme 업데이트
  README.md
Labels: 📄 Docs

#346 [FEAT] 이미지 성능 개선 (webp 변환)
  omocha-api/src/main/resources/application.yml
  omocha-domain/src/main/java/org/omocha/domain/image/ImageConverter.java
  omocha-domain/src/main/java/org/omocha/domain/image/ImageProvider.java
  omocha-infra/build.gradle
  omocha-infra/src/main/java/org/omocha/infra/image/AuctionImagesFactoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/image/FileNameGenerator.java
  omocha-infra/src/main/java/org/omocha/infra/image/ImageConverterImpl.java
  omocha-infra/src/main/java/org/omocha/infra/image/ImageServiceImpl.java
  omocha-infra/src/main/java/org/omocha/infra/image/S3Provider.java
Labels: 🐝 BE, 🐥 Feat

#348 [FEAT] 알림 기능 일부 구현
  omocha-api/src/main/java/org/omocha/api/auth/jwt/JwtProvider.java
  omocha-api/src/main/java/org/omocha/api/auth/jwt/RefreshTokenManager.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAccessDeniedHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAuthenticationEntryPointHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/GlobalExceptionHandler.java
  omocha-api/src/main/java/org/omocha/api/notification/NotificationApi.java
  omocha-api/src/main/java/org/omocha/api/notification/NotificationController.java
  omocha-api/src/main/java/org/omocha/api/notification/NotificationFacade.java
  omocha-api/src/main/java/org/omocha/api/notification/dto/NotificationDtoMapper.java
  omocha-api/src/main/resources/db/migration/V2.0.1__create_notification.sql
  omocha-api/src/main/resources/logback-spring.xml
  omocha-domain/src/main/java/org/omocha/domain/bid/BidReader.java
  omocha-domain/src/main/java/org/omocha/domain/bid/BidServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/SuccessCode.java
  omocha-domain/src/main/java/org/omocha/domain/common/util/JsonUtils.java
  omocha-domain/src/main/java/org/omocha/domain/conclude/ConcludeService.java
  omocha-domain/src/main/java/org/omocha/domain/conclude/ConcludeServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/exception/InvalidRefreshTokenException.java
  omocha-domain/src/main/java/org/omocha/domain/notification/Notification.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationCommand.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationInfo.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationReader.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationService.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationStore.java
  omocha-domain/src/main/java/org/omocha/domain/notification/enums/EventName.java
  omocha-domain/src/main/java/org/omocha/domain/notification/enums/NotificationCode.java
  omocha-infra/src/main/java/org/omocha/infra/bid/BidReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/bid/repository/BidRepository.java
  omocha-infra/src/main/java/org/omocha/infra/common/RedisPrefix.java
  omocha-infra/src/main/java/org/omocha/infra/notification/NotificationReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/notification/NotificationStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/notification/repository/NotificationRepository.java
  omocha-infra/src/main/java/org/omocha/infra/notification/repository/SseEmitterCache.java
  omocha-infra/src/main/java/org/omocha/infra/notification/repository/SseEmitterCacheImpl.java
Labels: 🐝 BE, 🐥 Feat

#351 [REFACTOR] email 발송 전 중복 확인 로직 추가
  omocha-api/src/main/java/org/omocha/api/mail/MailApi.java
  omocha-domain/src/main/java/org/omocha/domain/mail/MailServiceImpl.java
Labels: 🥲 Refactor, 🐝 BE

#352 [DEPLOY] 알림 추가 후 배포
  README.md
  omocha-api/src/main/java/org/omocha/api/auth/jwt/JwtProvider.java
  omocha-api/src/main/java/org/omocha/api/auth/jwt/RefreshTokenManager.java
  omocha-api/src/main/java/org/omocha/api/chat/dto/ChatDto.java
  omocha-api/src/main/java/org/omocha/api/chat/dto/ChatDtoMapper.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAccessDeniedHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAuthenticationEntryPointHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/GlobalExceptionHandler.java
  omocha-api/src/main/java/org/omocha/api/common/util/ValueObjectMapper.java
  omocha-api/src/main/java/org/omocha/api/mail/MailApi.java
  omocha-api/src/main/java/org/omocha/api/notification/NotificationApi.java
  omocha-api/src/main/java/org/omocha/api/notification/NotificationController.java
  omocha-api/src/main/java/org/omocha/api/notification/NotificationFacade.java
  omocha-api/src/main/java/org/omocha/api/notification/dto/NotificationDtoMapper.java
  omocha-api/src/main/resources/application.yml
  omocha-api/src/main/resources/db/migration/V2.0.1__create_notification.sql
  omocha-api/src/main/resources/logback-spring.xml
  omocha-api/src/test/java/org/omocha/api/bid/BidTest.java
  omocha-domain/src/main/java/org/omocha/domain/bid/BidCacheDto.java
  omocha-domain/src/main/java/org/omocha/domain/bid/BidInfo.java
  omocha-domain/src/main/java/org/omocha/domain/bid/BidReader.java
  omocha-domain/src/main/java/org/omocha/domain/bid/BidServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/bid/HighestBidManager.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/SuccessCode.java
  omocha-domain/src/main/java/org/omocha/domain/common/util/JsonUtils.java
  omocha-domain/src/main/java/org/omocha/domain/conclude/ConcludeService.java
  omocha-domain/src/main/java/org/omocha/domain/conclude/ConcludeServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/image/ImageConverter.java
  omocha-domain/src/main/java/org/omocha/domain/image/ImageProvider.java
  omocha-domain/src/main/java/org/omocha/domain/mail/MailServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/exception/InvalidRefreshTokenException.java
  omocha-domain/src/main/java/org/omocha/domain/notification/Notification.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationCommand.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationInfo.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationReader.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationService.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationStore.java
  omocha-domain/src/main/java/org/omocha/domain/notification/enums/EventName.java
  omocha-domain/src/main/java/org/omocha/domain/notification/enums/NotificationCode.java
  omocha-infra/build.gradle
  omocha-infra/src/main/java/org/omocha/infra/bid/BidReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/bid/BidStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/bid/repository/BidCacheRepository.java
  omocha-infra/src/main/java/org/omocha/infra/bid/repository/BidCacheRepositoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/bid/repository/BidRepository.java
  omocha-infra/src/main/java/org/omocha/infra/common/RedisPrefix.java
  omocha-infra/src/main/java/org/omocha/infra/common/config/RedisConfig.java
  omocha-infra/src/main/java/org/omocha/infra/image/AuctionImagesFactoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/image/FileNameGenerator.java
  omocha-infra/src/main/java/org/omocha/infra/image/ImageConverterImpl.java
  omocha-infra/src/main/java/org/omocha/infra/image/ImageServiceImpl.java
  omocha-infra/src/main/java/org/omocha/infra/image/S3Provider.java
  omocha-infra/src/main/java/org/omocha/infra/notification/NotificationReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/notification/NotificationStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/notification/repository/NotificationRepository.java
  omocha-infra/src/main/java/org/omocha/infra/notification/repository/SseEmitterCache.java
  omocha-infra/src/main/java/org/omocha/infra/notification/repository/SseEmitterCacheImpl.java
Labels: 🐝 BE, deploy

#354 [FIX[ redisprefix 중복 코드 제거
  omocha-infra/src/main/java/org/omocha/infra/common/RedisPrefix.java
Labels: 🔧 Fix, 🐝 BE

#355 [DEPLOY] 알림 설정 배포 실패 후 다시 배포
  omocha-infra/src/main/java/org/omocha/infra/common/RedisPrefix.java
Labels: 🐝 BE, deploy

#359 [FIX] ci/cd.yml
  .github/workflows/prod-CICD.yml
Labels: 🔧 Fix, 🐝 BE

#364 [DOCS] README.md 수정
  README.md
Labels: 📄 Docs, 🐝 BE

#362 [REFACTOR] mail Template , ThreadPool Custom
  omocha-api/src/main/resources/templates/AuthCode.ftl
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/mail/exception/MailSendFailException.java
  omocha-domain/src/main/java/org/omocha/domain/mail/exception/MailTemplateFailException.java
  omocha-infra/build.gradle
  omocha-infra/src/main/java/org/omocha/infra/common/config/FreeMarkerConfig.java
  omocha-infra/src/main/java/org/omocha/infra/common/config/MailAsyncConfiguration.java
  omocha-infra/src/main/java/org/omocha/infra/mail/MailSenderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/mail/template/AuthCodeTemplate.java
  omocha-infra/src/main/java/org/omocha/infra/mail/template/MailTemplate.java
  omocha-infra/src/main/java/org/omocha/infra/mail/template/TemplateStrategy.java
Labels: 🥲 Refactor, 🐝 BE

#366 [FEAT] 알림 API 및 SSE 구현
  omocha-api/src/main/java/org/omocha/api/bid/BidFacade.java
  omocha-api/src/main/java/org/omocha/api/bid/ConcludeScheduler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/GlobalExceptionHandler.java
  omocha-api/src/main/java/org/omocha/api/notification/NotificationApi.java
  omocha-api/src/main/java/org/omocha/api/notification/NotificationController.java
  omocha-api/src/main/java/org/omocha/api/notification/NotificationFacade.java
  omocha-api/src/main/java/org/omocha/api/notification/dto/NotificationDto.java
  omocha-api/src/main/java/org/omocha/api/notification/dto/NotificationDtoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/bid/BidServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/SuccessCode.java
  omocha-domain/src/main/java/org/omocha/domain/common/exception/json/JsonDeserializationException.java
  omocha-domain/src/main/java/org/omocha/domain/common/exception/json/JsonSerializationException.java
  omocha-domain/src/main/java/org/omocha/domain/common/util/JsonUtils.java
  omocha-domain/src/main/java/org/omocha/domain/conclude/ConcludeService.java
  omocha-domain/src/main/java/org/omocha/domain/conclude/ConcludeServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationCommand.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationReader.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationService.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/notification/NotificationStore.java
  omocha-domain/src/main/java/org/omocha/domain/notification/exception/NotificationAccessException.java
  omocha-domain/src/main/java/org/omocha/domain/notification/exception/NotificationException.java
  omocha-domain/src/main/java/org/omocha/domain/notification/exception/NotificationNotFoundException.java
  omocha-infra/src/main/java/org/omocha/infra/common/RedisPrefix.java
  omocha-infra/src/main/java/org/omocha/infra/notification/NotificationReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/notification/NotificationStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/notification/repository/NotificationRepository.java
  omocha-infra/src/main/java/org/omocha/infra/notification/repository/SseEmitterCache.java
  omocha-infra/src/main/java/org/omocha/infra/notification/repository/SseEmitterCacheImpl.java
Labels: 🐝 BE, 🐥 Feat

#368 [FIX] 알림 LastEventId를 Header => RequestParam으로 변경
  omocha-api/src/main/java/org/omocha/api/notification/NotificationController.java
Labels: 🔧 Fix, 🐝 BE

#369 [DEPLOY] 알림 기능 개발서버 배포
  README.md
  omocha-api/src/main/java/org/omocha/api/notification/NotificationController.java
Labels: 🐝 BE, deploy

#372 [DOCS] Readme update
  README.md
Labels: 📄 Docs, 🐝 BE

#375 [REFACTOR] 메일 인증 잦은 재시도 방지
  omocha-api/src/main/java/org/omocha/api/mail/MailApi.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/mail/CodeCacheReader.java
  omocha-domain/src/main/java/org/omocha/domain/mail/CodeManager.java
  omocha-domain/src/main/java/org/omocha/domain/mail/exception/MailRetryExcessException.java
  omocha-infra/src/main/java/org/omocha/infra/mail/CodeCacheReaderImpl.java
Labels: 🥲 Refactor, 🐝 BE

#373 [REFACTOR] 낙찰 로직 auction 조회 시 endDate Between으로 변경
  omocha-infra/src/main/java/org/omocha/infra/auction/AuctionReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/auction/repository/AuctionRepository.java
Labels: 🥲 Refactor, 🐝 BE

#378 [DEPLOY] Staging 최종 배포
  README.md
  omocha-api/src/main/java/org/omocha/api/mail/MailApi.java
  omocha-domain/src/main/java/org/omocha/domain/common/code/ErrorCode.java
  omocha-domain/src/main/java/org/omocha/domain/mail/CodeCacheReader.java
  omocha-domain/src/main/java/org/omocha/domain/mail/CodeManager.java
  omocha-domain/src/main/java/org/omocha/domain/mail/exception/MailRetryExcessException.java
  omocha-infra/src/main/java/org/omocha/infra/auction/AuctionReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/auction/repository/AuctionRepository.java
  omocha-infra/src/main/java/org/omocha/infra/mail/CodeCacheReaderImpl.java
Labels: 🐝 BE, deploy

#382 [DEPLOY] 알림 추가 후 배포
  omocha-api/src/main/resources/application.yml
Labels: 🐝 BE, deploy
