Repository Kernel360/F2-omocha-BE, pull requests merged in 2024-10, with the labels that each got.

#24 [FEAT] 전체 게시글 조회 수정
  .github/workflows/deploy-CICD.yml
  build.gradle
  omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
  omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionApi.java
  omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionController.java
  omocha-client/src/main/java/org/auction/client/auction/interfaces/response/AuctionListResponse.java
  omocha-client/src/main/java/org/auction/client/common/code/AuctionCode.java
  omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
  omocha-client/src/main/java/org/auction/client/exception/member/InvalidMemberException.java
  omocha-client/src/main/java/org/auction/client/jwt/UserPrincipal.java
  omocha-client/src/main/resources/application.yml
  omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/AuctionRepository.java
  omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/condition/AuctionSearchCondition.java
  omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/custom/AuctionRepositoryCustom.java
  omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/custom/AuctionRepositoryImpl.java
Labels: 🔧 Fix, 🐝 BE, 🐥 Feat

#19 [FEAT] 입찰 기능 추가
  omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
  omocha-client/src/main/java/org/auction/client/bid/application/HighestBid.java
  omocha-client/src/main/java/org/auction/client/bid/interfaces/BidApi.java
  omocha-client/src/main/java/org/auction/client/bid/interfaces/BidController.java
  omocha-client/src/main/java/org/auction/client/bid/interfaces/request/CreateBidRequest.java
  omocha-client/src/main/java/org/auction/client/bid/interfaces/response/BidResponse.java
  omocha-client/src/main/java/org/auction/client/bid/interfaces/response/CreateBidResponse.java
  omocha-client/src/main/java/org/auction/client/common/code/AuctionCode.java
  omocha-client/src/main/java/org/auction/client/common/code/BidCode.java
  omocha-client/src/main/java/org/auction/client/exception/auction/AuctionIllegalStateException.java
  omocha-client/src/main/java/org/auction/client/exception/bid/BidException.java
  omocha-client/src/main/java/org/auction/client/exception/bid/BidIllegalArgumentException.java
  omocha-domain/src/main/java/org/auction/domain/bid/entity/BidEntity.java
  omocha-domain/src/main/java/org/auction/domain/bid/infrastructure/BidRepository.java
  omocha-domain/src/main/java/org/auction/domain/common/domain/entity/CreateTimeTrackableEntity.java
Labels: 🔧 Fix, 🥲 Refactor, 🐝 BE, 🐥 Feat

#26 [FIX] JWT Filter 에러 수정
  omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionController.java
  omocha-client/src/main/java/org/auction/client/common/code/AuctionErrorCode.java
  omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
  omocha-client/src/main/java/org/auction/client/config/security/filter/JwtAuthFilter.java
  omocha-client/src/main/java/org/auction/client/exception/GlobalExceptionHandler.java
  omocha-client/src/main/java/org/auction/client/jwt/application/JwtService.java
  omocha-client/src/main/java/org/auction/client/jwt/util/JwtGenerator.java
  omocha-client/src/main/java/org/auction/client/member/interfaces/request/MemberCreateRequest.java
  omocha-client/src/main/java/org/auction/client/member/interfaces/response/MemberLoginResponse.java
Labels: 🔧 Fix, 🐝 BE

#28 [FIX] GlobalExceptionHandler 수정
  omocha-client/src/main/java/org/auction/client/config/swagger/SwaggerConfig.java
  omocha-client/src/main/java/org/auction/client/exception/GlobalExceptionHandler.java
  omocha-client/src/main/java/org/auction/client/exception/bid/BidException.java
Labels: 🔧 Fix, 🐝 BE

#30 [FIX] 프론트 배포 후 cors 오류 수정
  omocha-client/src/main/java/org/auction/client/config/security/CustomCorsConfig.java
  omocha-client/src/main/java/org/auction/client/jwt/application/JwtService.java
  omocha-client/src/main/resources/application.yml
Labels: 🔧 Fix, 🐝 BE

#31 [FEAT] OAuth 로그인 구현
  omocha-client/build.gradle
  omocha-client/src/main/java/org/auction/client/common/code/OauthCode.java
  omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
  omocha-client/src/main/java/org/auction/client/config/security/filter/JwtAuthFilter.java
  omocha-client/src/main/java/org/auction/client/config/security/handler/CustomAccessDeniedHandler.java
  omocha-client/src/main/java/org/auction/client/config/security/handler/CustomAuthenticationEntryPointHandler.java
  omocha-client/src/main/java/org/auction/client/config/security/handler/OAuth2FailureHandler.java
  omocha-client/src/main/java/org/auction/client/config/security/handler/OAuth2SuccessHandler.java
  omocha-client/src/main/java/org/auction/client/exception/oauth/OauthException.java
  omocha-client/src/main/java/org/auction/client/exception/oauth/UnsupportedOAuthProviderException.java
  omocha-client/src/main/java/org/auction/client/jwt/UserPrincipal.java
  omocha-client/src/main/java/org/auction/client/jwt/application/JwtService.java
  omocha-client/src/main/java/org/auction/client/oauth/OAuth2UserInfo.java
  omocha-client/src/main/java/org/auction/client/oauth/application/CustomOAuth2UserService.java
  omocha-client/src/main/resources/application.yml
  omocha-client/src/main/resources/static/favicon.ico
Labels: 🔧 Fix, 🐝 BE, 🐥 Feat

#35 [FIX] 입찰 기능 수정 및 @Authentication 수정
  omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
  omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionApi.java
  omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionController.java
  omocha-client/src/main/java/org/auction/client/auction/interfaces/request/CreateAuctionRequest.java
  omocha-client/src/main/java/org/auction/client/auction/interfaces/response/AuctionDetailResponse.java
  omocha-client/src/main/java/org/auction/client/auction/interfaces/response/AuctionListResponse.java
  omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
  omocha-client/src/main/java/org/auction/client/bid/interfaces/BidApi.java
  omocha-client/src/main/java/org/auction/client/bid/interfaces/BidController.java
  omocha-client/src/main/java/org/auction/client/common/code/BidCode.java
  omocha-client/src/main/java/org/auction/client/jwt/UserPrincipal.java
  omocha-client/src/main/java/org/auction/client/jwt/application/CustomUserDetailsService.java
  omocha-client/src/main/resources/logback-spring-local.xml
  omocha-domain/src/main/java/org/auction/domain/auction/domain/entity/AuctionEntity.java
  omocha-domain/src/main/java/org/auction/domain/member/domain/entity/MemberEntity.java
Labels: 🔧 Fix, 🐝 BE, 🐥 Feat

#42 [FEAT] 경매 상태(Status) 조회 추가
  build.gradle
  omocha-client/build.gradle
  omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
  omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionApi.java
  omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionController.java
  omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
  omocha-domain/src/main/java/org/auction/domain/auction/domain/enums/AuctionStatus.java
  omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/custom/AuctionRepositoryCustom.java
  omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/custom/AuctionRepositoryImpl.java
Labels: 🐝 BE, 🐥 Feat

#44 [FIX] AWS ELB Health Check 경로 추가
  omocha-client/src/main/java/org/auction/client/aws/interfaces/HealthCheckController.java
  omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
Labels: 🔧 Fix, 🐝 BE

#46 [FIX] local.omocha-auction.com cors 에러 수정
  omocha-client/src/main/java/org/auction/client/config/security/CustomCorsConfig.java
Labels: 🔧 Fix, 🐝 BE

#47 [FIX] Github action CI/CD 배포 수정
  .github/workflows/deploy-CICD.yml
  docker-compose.yaml
Labels: 🔧 Fix, 🐝 BE

#38 [FEAT] QnA CRUD 구현
  omocha-client/src/main/java/org/auction/client/common/code/QnACode.java
  omocha-client/src/main/java/org/auction/client/exception/GlobalExceptionHandler.java
  omocha-client/src/main/java/org/auction/client/exception/qna/QnaException.java
  omocha-client/src/main/java/org/auction/client/exception/qna/QnaNotAllowedException.java
  omocha-client/src/main/java/org/auction/client/exception/qna/QnaNotFoundException.java
  omocha-client/src/main/java/org/auction/client/qna/application/AnswerService.java
  omocha-client/src/main/java/org/auction/client/qna/application/QuestionService.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/AnswerApi.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/AnswerController.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/QuestionApi.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/QuestionController.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/request/CreateAnswerRequest.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/request/CreateQuestionRequest.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/request/ModifyAnswerRequest.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/request/ModifyQuestionRequest.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/response/AnswerResponse.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/response/CreateAnswerResponse.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/response/CreateQuestionResponse.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/response/QuestionListResponse.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/response/QuestionResponse.java
  omocha-domain/src/main/java/org/auction/domain/qna/domain/entity/AnswerEntity.java
  omocha-domain/src/main/java/org/auction/domain/qna/domain/entity/QuestionEntity.java
  omocha-domain/src/main/java/org/auction/domain/qna/infrastructure/AnswerRepository.java
  omocha-domain/src/main/java/org/auction/domain/qna/infrastructure/QuestionRepository.java
  omocha-domain/src/main/java/org/auction/domain/qna/infrastructure/custom/QuestionRepositoryCustom.java
  omocha-domain/src/main/java/org/auction/domain/qna/infrastructure/custom/QuestionRepositoryImpl.java
Labels: 🐝 BE, 🐥 Feat

#49 [FIX] Cookie 만료시간 수정
  omocha-client/src/main/java/org/auction/client/jwt/application/JwtService.java
Labels: 🔧 Fix, 🐝 BE

#51 [FEAT] 채팅방 조회 구현
  omocha-client/build.gradle
  omocha-client/src/main/java/org/auction/client/chat/application/ChatRoomService.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/ChatRoomApi.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/ChatRoomController.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/response/ChatRoomListResponse.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/response/CreateChatRoomResponse.java
  omocha-client/src/main/java/org/auction/client/common/code/BidCode.java
  omocha-client/src/main/java/org/auction/client/config/chat/WebSocketConfig.java
  omocha-client/src/main/java/org/auction/client/config/swagger/SwaggerConfig.java
  omocha-client/src/main/java/org/auction/client/exception/GlobalExceptionHandler.java
  omocha-client/src/main/java/org/auction/client/exception/bid/NoBidsException.java
  omocha-client/src/main/java/org/auction/client/exception/chat/ChatException.java
  omocha-client/src/main/java/org/auction/client/exception/chat/ChatRoomAccessException.java
  omocha-client/src/main/java/org/auction/client/exception/chat/ChatRoomAlreadyExistsException.java
  omocha-client/src/main/java/org/auction/client/exception/chat/ChatRoomNotFoundException.java
  omocha-client/src/main/java/org/auction/client/exception/chat/SellerIsBuyerException.java
  omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/custom/AuctionRepositoryImpl.java
  omocha-domain/src/main/java/org/auction/domain/chat/domain/entity/ChatRoomEntity.java
  omocha-domain/src/main/java/org/auction/domain/chat/domain/enums/MessageType.java
  omocha-domain/src/main/java/org/auction/domain/chat/infrastructure/ChatRoomRepository.java
  omocha-domain/src/main/java/org/auction/domain/member/domain/entity/MemberEntity.java
Labels: 🐝 BE, 🐥 Feat

#53 [REFACTOR] QnA parameter 수정
  omocha-client/src/main/java/org/auction/client/config/swagger/SwaggerConfig.java
  omocha-client/src/main/java/org/auction/client/qna/application/QuestionService.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/QuestionApi.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/QuestionController.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/request/ModifyAnswerRequest.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/response/CreateAnswerResponse.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/response/CreateQuestionResponse.java
Labels: 🥲 Refactor, 🐝 BE

#56 [FIX] fetchjoin 제거 후 @BatchSize 사용
  omocha-domain/src/main/java/org/auction/domain/auction/domain/entity/AuctionEntity.java
Labels: 🔧 Fix, 🐝 BE

#58 [FIX] chatcode 누락 추가
  omocha-client/src/main/java/org/auction/client/common/code/ChatCode.java
Labels: ⚒️ Hotfix, 🐝 BE

#60 [FEAT] mypage 기능 추가
  omocha-client/src/main/java/org/auction/client/common/code/MypageCode.java
  omocha-client/src/main/java/org/auction/client/config/swagger/SwaggerConfig.java
  omocha-client/src/main/java/org/auction/client/exception/mypage/MypageException.java
  omocha-client/src/main/java/org/auction/client/mypage/application/MypageService.java
  omocha-client/src/main/java/org/auction/client/mypage/interfaces/MypageApi.java
  omocha-client/src/main/java/org/auction/client/mypage/interfaces/MypageController.java
  omocha-client/src/main/java/org/auction/client/mypage/interfaces/response/MemberInfoResponse.java
  omocha-client/src/main/java/org/auction/client/mypage/interfaces/response/MypageAuctionListResponse.java
  omocha-client/src/main/java/org/auction/client/mypage/interfaces/response/MypageBidListResponse.java
  omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/custom/AuctionRepositoryCustom.java
  omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/custom/AuctionRepositoryImpl.java
  omocha-domain/src/main/java/org/auction/domain/bid/infrastructure/BidRepository.java
  omocha-domain/src/main/java/org/auction/domain/bid/infrastructure/custom/BidRepositoryCustom.java
  omocha-domain/src/main/java/org/auction/domain/bid/infrastructure/custom/BidRepositoryImpl.java
Labels: 🐝 BE, 🐥 Feat

#62 [FEAT] 채팅 STOMP 방식, 나의 채팅방 전체 조회, 채팅방 상세 조회를 무한 스크롤로 구현
  omocha-client/src/main/java/org/auction/client/chat/application/ChatRoomService.java
  omocha-client/src/main/java/org/auction/client/chat/application/ChatService.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/ChatController.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/ChatRoomApi.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/ChatRoomController.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/request/ChatMessageRequest.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/response/ChatMessageResponse.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/response/ChatRoomDetailsResponse.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/response/ChatRoomInfoDto.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/response/ChatRoomListResponse.java
  omocha-client/src/main/java/org/auction/client/common/code/ChatCode.java
  omocha-client/src/main/java/org/auction/client/common/dto/SliceResponse.java
  omocha-client/src/main/java/org/auction/client/common/dto/SortResponse.java
  omocha-client/src/main/java/org/auction/client/config/chat/WebSocketConfig.java
  omocha-client/src/main/java/org/auction/client/config/swagger/SwaggerConfig.java
  omocha-client/src/main/resources/application.yml
  omocha-client/src/main/resources/logback-spring-prod.xml
  omocha-domain/src/main/java/org/auction/domain/chat/domain/entity/ChatEntity.java
  omocha-domain/src/main/java/org/auction/domain/chat/domain/entity/ChatRoomEntity.java
  omocha-domain/src/main/java/org/auction/domain/chat/infrastructure/ChatRepository.java
  omocha-domain/src/main/java/org/auction/domain/chat/infrastructure/ChatRoomRepository.java
  omocha-domain/src/main/java/org/auction/domain/chat/infrastructure/custom/ChatRepositoryCustom.java
  omocha-domain/src/main/java/org/auction/domain/chat/infrastructure/custom/ChatRepositoryImpl.java
  omocha-domain/src/main/java/org/auction/domain/chat/infrastructure/custom/ChatRoomRepositoryCustom.java
  omocha-domain/src/main/java/org/auction/domain/chat/infrastructure/custom/ChatRoomRepositoryImpl.java
  omocha-domain/src/main/java/org/auction/domain/member/domain/entity/MemberEntity.java
Labels: 🐝 BE, 🐥 Feat

#66 [FEAT] Logout API 구현
  omocha-client/src/main/java/org/auction/client/common/code/MemberCode.java
  omocha-client/src/main/java/org/auction/client/member/interfaces/AuthApi.java
  omocha-client/src/main/java/org/auction/client/member/interfaces/AuthController.java
Labels: 🐝 BE, 🐥 Feat

#68 [FIX] 배포환경 Redirect Uri 수정
  omocha-client/src/main/resources/application.yml
  omocha-client/src/main/resources/logback-spring-local.xml
  omocha-client/src/main/resources/logback-spring-prod.xml
Labels: 🔧 Fix, 🐝 BE

#71 [FIX] CD시 docker hub login 문제 해결
  .github/workflows/deploy-CICD.yml
Labels: 🔧 Fix, 🐝 BE

#72 [FIX] Controller단 Override 추가
  omocha-client/src/main/java/org/auction/client/chat/interfaces/ChatRoomController.java
  omocha-client/src/main/java/org/auction/client/mypage/interfaces/MypageController.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/AnswerController.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/QuestionController.java
Labels: 🔧 Fix, 🐝 BE

#73 [FEAT] CD 시 docker sudo 부여
  .github/workflows/deploy-CICD.yml
  docker-compose.yaml
  omocha-client/src/main/resources/application.yml
Labels: 🔧 Fix, 🐝 BE

#75 [HOTFIX] 입찰내역이 없는 auction 임시 처리
  omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
  omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
  omocha-client/src/main/java/org/auction/client/chat/application/ChatRoomService.java
Labels: ⚒️ Hotfix, 🐝 BE

#79 [FIX] OAuth username 받도록 처리
  omocha-client/src/main/java/org/auction/client/bid/application/ConcludeService.java
  omocha-client/src/main/java/org/auction/client/oauth/OAuth2UserInfo.java
  omocha-domain/src/main/java/org/auction/domain/member/domain/entity/MemberEntity.java
Labels: 🔧 Fix, 🐝 BE

#81 [FEAT] swagger tag 추가
  omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionApi.java
  omocha-client/src/main/java/org/auction/client/bid/interfaces/BidApi.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/ChatRoomApi.java
  omocha-client/src/main/java/org/auction/client/config/swagger/SwaggerConfig.java
  omocha-client/src/main/java/org/auction/client/member/interfaces/AuthApi.java
  omocha-client/src/main/java/org/auction/client/mypage/interfaces/MypageApi.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/AnswerApi.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/QuestionApi.java
  omocha-client/src/main/resources/logback-spring-local.xml
  omocha-client/src/main/resources/logback-spring-prod.xml
Labels: 🐝 BE, 🐥 Feat

#87 [FIX] WebSocketConfig setAllowedOriginPatterns 추가
  omocha-client/src/main/java/org/auction/client/config/chat/WebSocketConfig.java
Labels: 🔧 Fix, 🐝 BE

#89 [FIX] WebSocket 엔드포인트 추가 및 변경
  omocha-client/src/main/java/org/auction/client/config/chat/WebSocketConfig.java
  omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
Labels: 🔧 Fix, 🐝 BE

#91 [FIX] ChatController 수정, 유저 정보 프론트에서 받음
  omocha-client/src/main/java/org/auction/client/chat/application/ChatService.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/ChatController.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/request/ChatMessageRequest.java
Labels: 🔧 Fix, 🐝 BE

#84 [FIX] 입찰이 없는 경매에 대한 낙찰 로직 변경
  docker-compose.yaml
  omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
  omocha-client/src/main/java/org/auction/client/auction/interfaces/response/AuctionDetailResponse.java
  omocha-client/src/main/java/org/auction/client/auction/interfaces/response/AuctionListResponse.java
  omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
  omocha-client/src/main/java/org/auction/client/bid/application/ConcludeService.java
  omocha-client/src/main/java/org/auction/client/bid/application/HighestBid.java
  omocha-client/src/main/java/org/auction/client/chat/application/ChatRoomService.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/response/ChatRoomInfoDto.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/response/CreateChatRoomResponse.java
  omocha-client/src/main/java/org/auction/client/config/security/filter/JwtAuthFilter.java
  omocha-client/src/main/java/org/auction/client/mypage/application/MypageService.java
  omocha-client/src/main/java/org/auction/client/mypage/interfaces/response/MypageAuctionListResponse.java
  omocha-domain/src/main/java/org/auction/domain/auction/domain/enums/AuctionStatus.java
  omocha-domain/src/main/java/org/auction/domain/chat/domain/entity/ChatRoomEntity.java
Labels: 🔧 Fix, 🐝 BE

#92 [FIX] 입찰 걸린 경매 삭제 불가 처리
  omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
  omocha-client/src/main/java/org/auction/client/common/code/AuctionCode.java
  omocha-client/src/main/java/org/auction/client/exception/auction/AuctionHasBidsException.java
Labels: 🔧 Fix, 🐝 BE

#95 [FIX] 입찰 로직에 Exception 추가
  omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
  omocha-client/src/main/java/org/auction/client/common/code/BidCode.java
  omocha-client/src/main/java/org/auction/client/config/security/handler/CustomAuthenticationEntryPointHandler.java
  omocha-client/src/main/java/org/auction/client/exception/bid/InvalidBidUnitException.java
  omocha-client/src/main/java/org/auction/client/exception/bid/SelfBidNotAllowedException.java
Labels: 🔧 Fix, 🐝 BE

#97 [FIX] Auction 관련 reponse에 속성 추가
  omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
  omocha-client/src/main/java/org/auction/client/auction/interfaces/response/AuctionDetailResponse.java
  omocha-client/src/main/java/org/auction/client/auction/interfaces/response/AuctionListResponse.java
  omocha-client/src/main/java/org/auction/client/bid/application/ConcludeService.java
  omocha-domain/src/main/java/org/auction/domain/bid/infrastructure/ConcludeRepository.java
Labels: 🔧 Fix, 🐝 BE

#100 [FIX] 입찰 BidUnit 체크 오류 수정
  omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
Labels: 🔧 Fix, 🐝 BE

#107 [FEAT] Cursor Pagination 및 정렬 순서 수정
  omocha-client/src/main/java/org/auction/client/bid/application/ConcludeService.java
  omocha-client/src/main/java/org/auction/client/chat/application/ChatRoomService.java
  omocha-client/src/main/java/org/auction/client/chat/application/ChatService.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/ChatRoomApi.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/ChatRoomController.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/response/ChatRoomDetailsResponse.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/response/ChatRoomInfoDto.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/response/ChatRoomListResponse.java
  omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
  omocha-domain/src/main/java/org/auction/domain/chat/domain/dto/ChatRoomInfoDto.java
  omocha-domain/src/main/java/org/auction/domain/chat/infrastructure/custom/ChatRepositoryCustom.java
  omocha-domain/src/main/java/org/auction/domain/chat/infrastructure/custom/ChatRepositoryImpl.java
  omocha-domain/src/main/java/org/auction/domain/chat/infrastructure/custom/ChatRoomRepositoryCustom.java
  omocha-domain/src/main/java/org/auction/domain/chat/infrastructure/custom/ChatRoomRepositoryImpl.java
Labels: 🐝 BE, 🐥 Feat

#98 [FEAT] QnA 통합 조회
  omocha-client/src/main/java/org/auction/client/common/code/QnACode.java
  omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
  omocha-client/src/main/java/org/auction/client/exception/qna/QnaResponseStatusException.java
  omocha-client/src/main/java/org/auction/client/qna/application/AnswerService.java
  omocha-client/src/main/java/org/auction/client/qna/application/QuestionService.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/QuestionApi.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/QuestionController.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/response/QnaServiceResponse.java
  omocha-client/src/main/java/org/auction/client/qna/interfaces/response/QuestionResponse.java
  omocha-domain/src/main/java/org/auction/domain/qna/domain/entity/AnswerEntity.java
  omocha-domain/src/main/java/org/auction/domain/qna/domain/entity/QuestionEntity.java
  omocha-domain/src/main/java/org/auction/domain/qna/domain/response/QnaDomainResponse.java
  omocha-domain/src/main/java/org/auction/domain/qna/infrastructure/AnswerRepository.java
  omocha-domain/src/main/java/org/auction/domain/qna/infrastructure/QuestionRepository.java
  omocha-domain/src/main/java/org/auction/domain/qna/infrastructure/custom/QuestionRepositoryCustom.java
  omocha-domain/src/main/java/org/auction/domain/qna/infrastructure/custom/QuestionRepositoryImpl.java
Labels: 🐝 BE, 🐥 Feat

#110 [FIX] 배포환경 로그아웃 시 쿠키 사라지지 않는 문제 해결
  omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
  omocha-client/src/main/java/org/auction/client/jwt/application/JwtService.java
  omocha-client/src/main/java/org/auction/client/jwt/util/JwtUtil.java
Labels: 🔧 Fix, 🐝 BE

#112 [FIX] favicon 오류 문제 해결 test
  omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionController.java
  omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
  omocha-client/src/main/resources/logback-spring-prod.xml
Labels: 🔧 Fix, 🐝 BE

#113 [FEAT] 현재가 조회 API 추가
  omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
  omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
  omocha-client/src/main/java/org/auction/client/bid/application/ConcludeService.java
  omocha-client/src/main/java/org/auction/client/bid/interfaces/BidApi.java
  omocha-client/src/main/java/org/auction/client/bid/interfaces/BidController.java
  omocha-client/src/main/java/org/auction/client/bid/interfaces/response/NowPriceResponse.java
  omocha-client/src/main/java/org/auction/client/chat/interfaces/ChatRoomController.java
  omocha-client/src/main/java/org/auction/client/common/code/BidCode.java
  omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
  omocha-client/src/main/java/org/auction/client/mypage/application/MypageService.java
Labels: 🔧 Fix, 🐝 BE, 🐥 Feat

#114 [FIX] validate email 할 때 RequestBody => RequestParam으로 변경
  data/postgresql/index.sql
  omocha-client/src/main/java/org/auction/client/common/code/MemberCode.java
  omocha-client/src/main/java/org/auction/client/jwt/application/JwtService.java
  omocha-client/src/main/java/org/auction/client/member/application/MemberService.java
  omocha-client/src/main/java/org/auction/client/member/interfaces/AuthApi.java
  omocha-client/src/main/java/org/auction/client/member/interfaces/AuthController.java
Labels: 🔧 Fix, 🐝 BE

#116 [FIX] 현재가와 동일한 입찰가 막기
  omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
  omocha-client/src/main/java/org/auction/client/common/code/BidCode.java
  omocha-client/src/main/java/org/auction/client/jwt/application/JwtService.java
Labels: 🔧 Fix, 🐝 BE

#118 [FIX] resetCookie를 setCookie와 동일한 형식으로 변경
  omocha-client/src/main/java/org/auction/client/jwt/application/JwtService.java
  omocha-client/src/main/java/org/auction/client/jwt/util/JwtUtil.java
Labels: 🔧 Fix, 🐝 BE

#119 [DOCS] README 작성
  README.md
Labels: 📄 Docs, 🐝 BE

#122 [FIX] 현재가 조회에 API 호출 시간 추가
  omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
  omocha-client/src/main/java/org/auction/client/bid/interfaces/response/NowPriceResponse.java
  omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
Labels: 🔧 Fix, 🐝 BE

#125 [DOCS] README 기술 스택 추가
  README.md
Labels: 📄 Docs, 🐝 BE

#127 README 반영
  README.md
Labels: 📄 Docs, 🐝 BE

#137 [REFACTOR] Security 리팩토링
  build.gradle
  omocha-api/build.gradle
  omocha-api/src/main/java/org/omocha/api/common/config/CustomCorsConfig.java
  omocha-api/src/main/java/org/omocha/api/common/config/SecurityConfig.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAccessDeniedHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAuthenticationEntryPointHandler.java
Labels: 🥲 Refactor, 🐝 BE

#138 [REFACTOR] member 리팩토링
  build.gradle
  omocha-api/build.gradle
  omocha-api/src/main/java/org/omocha/api/application/MemberFacade.java
  omocha-api/src/main/java/org/omocha/api/common/config/CustomCorsConfig.java
  omocha-api/src/main/java/org/omocha/api/common/config/SecurityConfig.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAccessDeniedHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAuthenticationEntryPointHandler.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuthController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/MemberDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/MemberDtoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/member/.keep
  omocha-domain/src/main/java/org/omocha/domain/member/Member.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberCommand.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberInfo.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberReader.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberService.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberStore.java
  omocha-domain/src/main/java/org/omocha/domain/member/Role.java
  omocha-domain/src/main/java/org/omocha/domain/member/UserStatus.java
  omocha-infra/src/main/java/org/omocha/infra/MemberReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/MemberStoreImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/MemberRepository.java
Labels: 🥲 Refactor, 🐝 BE

#140 [REFACTOR] Branch 충돌 해결
  build.gradle
  omocha-api/src/main/java/org/omocha/api/common/config/CustomCorsConfig.java
  omocha-api/src/main/java/org/omocha/api/common/config/SecurityConfig.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAccessDeniedHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/CustomAuthenticationEntryPointHandler.java
Labels: 🥲 Refactor, 🐝 BE

#141 [REFACTOR] email 검증 수정
  omocha-api/src/main/java/org/omocha/api/application/MemberFacade.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuthController.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberValidator.java
  omocha-infra/src/main/java/org/omocha/infra/MemberValidatorImpl.java
Labels: 🥲 Refactor, 🐝 BE

#142 [REFACTOR]: member 관련 기능 리팩토링
  omocha-api/src/main/java/org/omocha/api/application/MemberFacade.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberReader.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberService.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberValidator.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberValidatorImpl.java
  omocha-infra/src/main/java/org/omocha/infra/MemberReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/MemberValidatorImpl.java
Labels: 🥲 Refactor, 🐝 BE

#143 [REFACTOR] JWT 관련 리팩토링
  omocha-api/src/main/java/org/omocha/api/application/MemberFacade.java
  omocha-api/src/main/java/org/omocha/api/common/auth/jwt/JwtCategory.java
  omocha-api/src/main/java/org/omocha/api/common/auth/jwt/JwtGenerator.java
  omocha-api/src/main/java/org/omocha/api/common/auth/jwt/JwtProvider.java
  omocha-api/src/main/java/org/omocha/api/common/auth/jwt/JwtUtil.java
  omocha-api/src/main/java/org/omocha/api/common/auth/jwt/RefreshTokenStore.java
  omocha-api/src/main/java/org/omocha/api/common/auth/jwt/UserPrincipal.java
  omocha-api/src/main/java/org/omocha/api/common/config/PasswordEncoderConfig.java
  omocha-api/src/main/java/org/omocha/api/common/config/SecurityConfig.java
  omocha-api/src/main/java/org/omocha/api/common/filter/JwtAuthFilter.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuthController.java
  omocha-domain/src/main/java/org/omocha/domain/exception/InvalidRefreshTokenException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/JwtTokenException.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberCommand.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberInfo.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberReader.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberService.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberValidatorImpl.java
  omocha-infra/src/main/java/org/omocha/infra/MemberReaderImpl.java
Labels: 🥲 Refactor, 🐝 BE

#145 [REFACTOR] OAuth2.0 관련 리팩토링
  omocha-api/src/main/java/org/omocha/api/common/auth/oauth/CustomOAuth2UserService.java
  omocha-api/src/main/java/org/omocha/api/common/auth/oauth/OAuth2UserInfo.java
  omocha-api/src/main/java/org/omocha/api/common/handler/OAuth2FailureHandler.java
  omocha-api/src/main/java/org/omocha/api/common/handler/OAuth2SuccessHandler.java
  omocha-domain/src/main/java/org/omocha/domain/exception/OauthException.java
  omocha-domain/src/main/java/org/omocha/domain/exception/UnsupportedOAuthProviderException.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
Labels: 🥲 Refactor, 🐝 BE

#147 [REFACTOR] Mypage 리팩토링
  omocha-api/src/main/java/org/omocha/api/application/MypageFacade.java
  omocha-api/src/main/java/org/omocha/api/common/config/SecurityConfig.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuthController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/MypageController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/MypageDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/MypageDtoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionReader.java
  omocha-domain/src/main/java/org/omocha/domain/member/MemberServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/member/mypage/MypageInfo.java
  omocha-domain/src/main/java/org/omocha/domain/member/mypage/MypageService.java
  omocha-domain/src/main/java/org/omocha/domain/member/mypage/MypageServiceImpl.java
  omocha-infra/src/main/java/org/omocha/infra/AuctionReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AuctionRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AuctionRepositoryImpl.java
Labels: 🥲 Refactor, 🐝 BE

#150 [FEAT] Thumnail 이미지 추가
  omocha-api/src/main/java/org/omocha/api/application/AuctionFacade.java
  omocha-api/src/main/java/org/omocha/api/interfaces/AuctionController.java
  omocha-api/src/main/java/org/omocha/api/interfaces/dto/AuctionDto.java
  omocha-api/src/main/java/org/omocha/api/interfaces/mapper/AuctionDtoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/Auction.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionCommand.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfo.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionInfoMapper.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionReader.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionService.java
  omocha-domain/src/main/java/org/omocha/domain/auction/AuctionServiceImpl.java
  omocha-domain/src/main/java/org/omocha/domain/common/BaseEntity.java
  omocha-domain/src/main/java/org/omocha/domain/image/ImageProvider.java
  omocha-infra/src/main/java/org/omocha/infra/AuctionImagesFactoryImpl.java
  omocha-infra/src/main/java/org/omocha/infra/AuctionReaderImpl.java
  omocha-infra/src/main/java/org/omocha/infra/S3Provider.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AuctionRepository.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AuctionRepositoryCustom.java
  omocha-infra/src/main/java/org/omocha/infra/repository/AuctionRepositoryImpl.java
Labels: 🥲 Refactor, 🐝 BE, 🐥 Feat
